AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ExpandZip:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      FunctionName: ExpandZip
      Runtime: nodejs6.10
      Policies: AmazonS3FullAccess
      Timeout: 120
      Environment:
        Variables:
          NODE_ENV: NODE_ENV
      Events:
        ZipUpload:
          Type: S3
          Properties:
            Bucket: !Ref Bucket
            Events: s3:ObjectCreated:*
  Bucket:
    Type: AWS::S3::Bucket